neuvector/manager

- admin/webapp/root/app_src/js/nv/nodeChart/graphController.js
- admin/webapp/root/app_src/package.json
> Adjust graph layout

- cli/prog/process.py
- cli/prog/system.py
// Constants for the Basline attribute
const (
ProfileBasic     string = "basic"			// disabled
ProfileZeroDrift string = "zero-drift"		// enabled
}
> The constant changes for process baseline profile

- admin/src/main/scala/com/neu/client/RestClient.scala
- build.sbt
- project/plugins.sbt
> Refactoring RestClient

- admin/webapp/root/app/views/profile.html
- admin/webapp/root/app_src/js/nv/setting/profileController.js
Resets profile form password-related fields on submission error.
| Before "Update Profile"  | After "Update Profile" |
| ------------- | ------------- |
| <img width="1512" alt="Screen Shot 2022-03-01 at 4 12 05 PM" src="https://user-images.githubusercontent.com/29556139/156271396-fe40e9e4-4462-45ec-ad0d-128ea5e6ea1d.png"> | <img width="1512" alt="Screen Shot 2022-03-01 at 4 12 42 PM" src="https://user-images.githubusercontent.com/29556139/156271408-2b842457-ae2c-4a69-954a-b7e7e371a516.png"> |
Addresses neuvector/neuvector#91
> NVSHAS-6195 Fix profile form submission logic

- cli/prog/system.py
add system configuration network service toggle to select cluster wide network policy mode
> NVSHAS-5545, in cli add system configuration network service toggle

- cli/prog/client.py
- cli/prog/system.py
Move AutoMode REST structure out of the "RESTSystemConfigConfig".
Affected command: 
"set system auto_mode config"
> NV5818: Mode automation, REST config data changed.

- admin/src/main/scala/com/neu/api/WorkloadService.scala
- admin/src/main/scala/com/neu/client/RestClient.scala
- admin/src/main/scala/com/neu/model/Policy.scala
- admin/src/main/scala/com/neu/model/PolicyJsonProtocol.scala
- admin/webapp/root/app/views/group.html
- admin/webapp/root/app/views/settings.html
- admin/webapp/root/app/views/workloads.html
- admin/webapp/root/app_src/i18n/en/en.json
- admin/webapp/root/app_src/i18n/zh_cn/zh_cn.json
- admin/webapp/root/app_src/js/nv/assets/containerController.js
- admin/webapp/root/app_src/js/nv/assets/containerService.js
- admin/webapp/root/app_src/js/nv/security/groupController.js
NVSHAS-5200: Add service account that deploys the pod;
NVSHAS-6273: UI: Configurations - Add service group mode automation;
NVSHAS-6279: Suggest display selected Network Service Policy Mode on Policy->Groups page;
> NVSHAS-5200;NVSHAS-6273;NVSHAS-6279

- admin/src/main/scala/com/neu/api/BaseService.scala
- admin/webapp/root/app_src/i18n/en/en.json
- admin/webapp/root/app_src/i18n/zh_cn/zh_cn.json
- admin/webapp/root/app_src/js/nv/security/complianceService.js
> NVSHAS-6340, NVSHAS-6298 (Refined style)

- .gitignore
- cli/prog/admission.py
Simple extension to include the new modules admission control rule.
Dependent on https://github.com/neuvector/neuvector/pull/328
> Nvshas 3842

- admin/webapp/root/app/views/workloads.html
- admin/webapp/root/app_src/js/nv/assets/containerController.js
Fix [NVSHAS-6569](https://jira.suse.com/browse/NVSHAS-6569), [NVSHAS-6570](https://jira.suse.com/browse/NVSHAS-6570)
Fixes containers page scan request propogation && exit node UI
> NVSHAS-6569 NVSHAS-6570

- admin/webapp/root/app_src/js/nv/dashboard/dashboardController.js
…ata) (Do not show neuvector_upgrade_info and scanner_upgrade_info)
> NVSHAS-6613 (Do not show neuvector_upgrade_info and scanner_upgrade_info)

- admin/webapp/websrc/app/routes/components/admission-rules/admission-rules.component.html
- admin/webapp/websrc/app/routes/components/admission-rules/admission-rules.component.ts
- admin/webapp/websrc/app/routes/components/controllers-grid/controllers-grid.component.ts
- admin/webapp/websrc/app/routes/components/enforcers-grid/enforcers-grid.component.ts
- admin/webapp/websrc/app/routes/components/multi-cluster-grid/multi-cluster-grid.component.ts
- admin/webapp/websrc/app/routes/components/network-rules/network-rules.component.html
- admin/webapp/websrc/app/routes/components/network-rules/network-rules.component.ts
- admin/webapp/websrc/app/routes/components/response-rules/response-rules.component.html
- admin/webapp/websrc/app/routes/components/response-rules/response-rules.component.ts
- admin/webapp/websrc/app/routes/components/scanners-grid/scanners-grid.component.ts
- admin/webapp/websrc/app/routes/dlp-sensors/dlp-sensors.component.html
- admin/webapp/websrc/app/routes/dlp-sensors/dlp-sensors.component.ts
- admin/webapp/websrc/app/routes/settings/configuration/support-form/support-form.component.ts
Fixes Support Log request bug.
Standardizes refresh buttons and fixes grid header styling on Admission Rules, Network Rules, Response Rules pages.
> NVSHAS-6668 (fix) && UI Standardization

- admin/webapp/websrc/app/routes/settings/common/helpers/index.ts
double colon characters in redirect uri of openid connect setting page
> NVSHAS-6835 

- admin/webapp/websrc/app/frame/header/header.component.ts
- admin/webapp/websrc/app/routes/components/multi-cluster-grid/multi-cluster-grid.component.ts
NVSHAS-6930 "Federated Policy" menu item should not be available on worker cluster UI
> NVSHAS-6930 

- admin/webapp/websrc/app/common/neuvector-formly/icon-input/icon-input.component.html
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form-config/constants/proxy-constants.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form.component.ts
Fixes [NVSHAS-7357] should show hidden wildcard characters after saml or openid connect configuration is saved
> NVSHAS-7357 (Settings > Configuration > Proxy)

- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.module.ts
NVHSAS-7404: reader/fedReader-role user should not see Accept button on Security Risks -> Vulnerabilities page
> NVSHAS-7404

- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items-charts/compliance-items-charts.component.ts
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items-table/compliance-items-table.component.ts
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items.component.html
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items.component.ts
- admin/webapp/websrc/app/routes/compliance/compliance.component.ts
- admin/webapp/websrc/app/routes/compliance/compliance.filter.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.filter.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-charts/vulnerability-items-charts.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
Fixes Vulnerabilities/Compliance advanced filter behavior:
- Now dynamically updates pie chart data based on filters
- Generated CSV/PDFs contains only filtered results
> NVSHAS-7537: Unable to download vulnerability report in CSV format after applying advance filter

- admin/webapp/websrc/app/common/services/scan.service.ts
- admin/webapp/websrc/app/routes/components/vulnerabilities-grid/vulnerabilities-grid.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
- admin/webapp/websrc/assets/i18n/en.json
- admin/webapp/websrc/assets/i18n/zh_cn.json
Adds `Feed Rating` field to Assets pages Vulnerability grids.
> NVSHAS-7523: Display RH CVSS score along with NVD score in NeuVector UI

- admin/webapp/websrc/app/common/styles/app/login-legacy.scss
- admin/webapp/websrc/app/routes/pages/login/login.component.html
> NVSHAS-6912 Make first time login and accepting EULA easier

- admin/webapp/websrc/app/common/neuvector-formly/formlyValidators.ts
- admin/webapp/websrc/app/routes/components/federated-policy-configuration/federated-config-form/federated-config-form.component.html
- admin/webapp/websrc/app/routes/components/federated-policy-configuration/federated-config-form/federated-config-form.component.ts
- admin/webapp/websrc/app/routes/components/federated-policy-configuration/federated-config-form/types/constants/webhook-constants.ts
[NVSHAS-7401](https://jira.suse.com/browse/NVSHAS-7401)
fedReader-role user should not have the chance to edit/add fed webhook
[NVSHAS-7583](https://jira.suse.com/browse/NVSHAS-7583)
working flow issue in fed webhook configuration page
> NVSHAS-7401, NVSHAS-7583

- admin/webapp/websrc/app/routes/components/namespaces-grid/namespaces-grid.component.ts
- admin/webapp/websrc/app/routes/namespaces/namespace-details/namespace-details.component.html
- admin/webapp/websrc/assets/i18n/en.json
- admin/webapp/websrc/assets/i18n/zh_cn.json
Removes duplicate info from detail view.
> NVSHAS-6695: Suggest to display namespace label on UI

- cli/prog/dlp.py
Support empty pattern for DLP rule in NV CLI
> NVSHAS-5759: Allow DLP rule without pattern in CLI

- admin/webapp/websrc/app/common/constants/map.constant.ts
- admin/webapp/websrc/app/routes/compliance-profile/compliance-profile.service.ts
Prevents `risk/compliance/template` API call if user lacks 'compliance_r' flag
> NVSHAS-7315: Resource access denied events are generated only for compliance profile page.

- admin/webapp/websrc/app/routes/network-activities/sniffer/sniffer.component.html
This commit will fix https://github.com/neuvector/neuvector/issues/723
> Fix font mismatch on sniffer component

- cli/prog/domain.py
- cli/requirements.txt
utils import was missing and caused a runtime exception
> NVSHAS-7707 - utils import missing

- admin/webapp/websrc/app/routes/registries/regestries-communication.service.ts
- admin/webapp/websrc/app/routes/registries/registries-table/add-registry-dialog/add-registry-dialog.component.ts
- admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.ts
Simplifies registry scan observable logic.
> NVSHAS-7647: registry view scanning refresh resets selection

- admin/webapp/websrc/app/routes/settings/configuration/csp-support-form/csp-support-form.component.ts
This reverts commit dd25669a094cc748a646e30f343e5edd8d78d32e.
> Revert "NVSHAS-7921: error msg is not readable when downloading the support config"

- admin/webapp/websrc/app/common/services/signatures.service.ts
- admin/webapp/websrc/app/routes/signature-verifiers/partial/add-edit-signature-verifiers-modal/add-edit-signature-verifiers-modal.component.html
- admin/webapp/websrc/app/routes/signature-verifiers/partial/add-edit-signature-verifiers-modal/add-edit-signature-verifiers-modal.component.ts
- admin/webapp/websrc/app/routes/signature-verifiers/partial/add-edit-verifiers-modal/add-edit-verifiers-modal.component.html
- admin/webapp/websrc/assets/i18n/en.json
- admin/webapp/websrc/assets/i18n/zh_cn.json
NVSHAS-7992: Missing comment field on Add/Edit verifier page
NVSHAS-7991: Missing "private" checkbox when creating a root of trust & there is no way to create a "public" root of trust
> NVSHAS-7992, NVSHAS-7991

- UI-Customization.md
- admin/src/main/scala/com/neu/api/AuthenticationService.scala
- admin/webapp/websrc/app/common/api/common-http.service.ts
- admin/webapp/websrc/app/common/constants/path.constant.ts
- admin/webapp/websrc/app/common/styles/app/login-legacy.scss
- admin/webapp/websrc/app/common/utils/common.utils.ts
- admin/webapp/websrc/app/common/variables/global.variable.ts
- admin/webapp/websrc/app/frame/header/header.component.html
- admin/webapp/websrc/app/frame/header/header.component.ts
- admin/webapp/websrc/app/routes/pages/login/eula/agreement/agreement.component.html
- admin/webapp/websrc/app/routes/pages/login/eula/agreement/agreement.component.ts
- admin/webapp/websrc/app/routes/pages/login/eula/eula.component.html
- admin/webapp/websrc/app/routes/pages/login/eula/eula.component.scss
- admin/webapp/websrc/app/routes/pages/login/eula/eula.component.ts
- admin/webapp/websrc/app/routes/pages/login/login.component.html
- admin/webapp/websrc/app/routes/pages/login/login.component.ts
- common/src/main/scala/com/neu/core/CommonSettings.scala
NVSHAS-6675 Customizable Login Banner
NVSHAS-7330 header/footer for classification level - RGS
> NVSHAS-6675, NVSHAS-7330 customize UI components by env

- admin/webapp/websrc/app/common/constants/global.constant.ts
- admin/webapp/websrc/app/common/services/signatures.service.ts
- admin/webapp/websrc/app/routes/components/admission-rules/partial/add-edit-admission-rule-modal/add-edit-admission-rule-modal.component.html
- admin/webapp/websrc/app/routes/components/admission-rules/partial/add-edit-admission-rule-modal/add-edit-admission-rule-modal.component.ts
- admin/webapp/websrc/app/routes/components/ui/multi-selector-dropdown/multi-selector-dropdown.component.ts
- admin/webapp/websrc/app/routes/signature-verifiers/partial/add-edit-signature-verifiers-modal/add-edit-signature-verifiers-modal.component.html
- admin/webapp/websrc/app/routes/signature-verifiers/partial/add-edit-signature-verifiers-modal/add-edit-signature-verifiers-modal.component.ts
- admin/webapp/websrc/assets/i18n/en.json
- admin/webapp/websrc/assets/i18n/zh_cn.json
[NVSHAS-8021: Change the Name field in "Sigstore Verifiers" page for c…
[NVSHAS-8020: Cannot create sigstore -> public root of trust on UI
[NVSHAS-8016: (UI) Add a new operator in Policy > Admission Control > …
[NVSHAS-7988: Some suggestions about imageVerifiers adm-ctrl rule valu…
> NVSHAS-8021, NVSHAS-8020, NVSHAS-8016, NVSHAS-7988

- admin/webapp/websrc/app/common/constants/global.constant.ts
- admin/webapp/websrc/app/common/services/notification.service.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form.component.html
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form.component.scss
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form.component.ts
NVSHAS-7755 error msg may not be readable after changing the auto scale setting in ui
> NVSHAS-7755 

- admin/src/main/scala/com/neu/model/SystemConfig.scala
- admin/src/main/scala/com/neu/model/SystemConfigJsonProtocol.scala
- admin/webapp/websrc/app/common/types/settings/config.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form-config/constants/syslog-constants.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form-config/index.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form.component.ts
- admin/webapp/websrc/assets/i18n/en.json
- admin/webapp/websrc/assets/i18n/zh_cn.json
Adds `syslog_cve_in_layers` field to Settings > Configuration > Syslog settings.
> NVSHAS-8135: UI work to support reporting vulnerabilities in layers

- admin/webapp/websrc/assets/i18n/en.json
- admin/webapp/websrc/assets/i18n/zh_cn.json
- cli/prog/admission.py
Update i18n and help text in CLI for annotation support.
> NVSHAS-7483: support annotations

- admin/webapp/websrc/app/common/types/registries/registries.ts
- admin/webapp/websrc/app/routes/components/vulnerabilities-grid/vulnerabilities-grid.component.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
> NVSHAS-7885: App scan result should report file, package and package version for each vuln

- admin/webapp/websrc/app/common/types/compliance/compliance.ts
- admin/webapp/websrc/app/common/types/vulnerabilities/vulnerabilities.ts
- admin/webapp/websrc/app/common/utils/common.utils.ts
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-item-details/compliance-item-details.component.html
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items-table/compliance-items-table-impact-cell/compliance-items-table-impact-cell.component.html
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items-table/compliance-items-table.component.ts
- admin/webapp/websrc/app/routes/compliance/compliance.filter.service.ts
- admin/webapp/websrc/app/routes/compliance/csv-generation/compliance-csv.service.ts
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/risks-view-report/risk-view-report-table/risk-view-report-table.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/csv-generation/vulnerabilities-csv.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-details/vulnerability-items-details.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table-impact-cell/vulnerability-items-table-impact-cell.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
NVSHAS-8050: Neuvector - Vulnerability advance filter report showingimages from all other namespace
NVSHAS-8046: NeuVector - Compliance Advanced filter for namespaces showing containers from other namespaces
> NVSHAS-8050, NVSHAS-8046

- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items-table/compliance-items-table-filter/compliance-items-table-filter.component.html
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items-table/compliance-items-table-filter/compliance-items-table-filter.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table-filter/vulnerability-items-table-filter.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table-filter/vulnerability-items-table-filter.component.ts
Allows Compliance/Vulnerabilities Namespaces filter to include non-autocomplete options
> NVSHAS-7970: NeuVector Advanced Filter - Namespaces Contains Option

- admin/src/main/scala/com/neu/api/AuthenticationService.scala
- admin/src/main/scala/com/neu/api/ClusterService.scala
- admin/src/main/scala/com/neu/api/DashboardService.scala
- admin/src/main/scala/com/neu/api/DeviceService.scala
- admin/src/main/scala/com/neu/api/GroupService.scala
- admin/src/main/scala/com/neu/api/NotificationService.scala
- admin/src/main/scala/com/neu/api/PolicyService.scala
- admin/src/main/scala/com/neu/api/RiskService.scala
- admin/src/main/scala/com/neu/api/Services.scala
- admin/src/main/scala/com/neu/api/SigstoreService.scala
- admin/src/main/scala/com/neu/api/WorkloadService.scala
- admin/src/main/scala/com/neu/web/StaticResources.scala
- common/src/main/resources/application.conf
NVSHAS-8217: Vuln Report - When XSS string is embedded in the request…
NVSHAS-8253: Security enhancement on Manager(Refactored respondWithNo…
> NVSHAS-8217, NVSHAS-8253

- admin/webapp/websrc/app/frame/sidebar/sidebar.component.html
- admin/webapp/websrc/app/frame/sidebar/sidebar.component.ts
Related case - NVSHAS-8244: UI Bug: Main Menu bleeding over copyright and version number
> NVSHAS-8267: At certain location, the menu "setting" is displayed but not clickable

- admin/webapp/websrc/app/common/services/network-rules.service.ts
- admin/webapp/websrc/app/routes/components/admission-rules/partial/add-edit-admission-rule-modal/add-edit-admission-rule-modal.component.html
NVSHAS-8230: Should not allow user input in the admission control setting's criteria box
NVSHAS-8182: Secondary sort for viewing network rules from group view - however, it should not be sortable
> NVSHAS-8182, NVSHAS-8230

- admin/webapp/websrc/app/common/api/policy-http.service.ts
- admin/webapp/websrc/app/routes/components/group-details/partial/custom-check/custom-check.component.html
- admin/webapp/websrc/app/routes/components/group-details/partial/custom-check/custom-check.component.ts
- admin/webapp/websrc/app/routes/registries/registries-table/add-registry-dialog/add-registry-form-configs/constants/constants.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
NVSHAS-8290: Enabling/Disabling users from editing custom check script on UI
CUSTOM_CHECK_CONTROL="disable"
admin or fedAdmin users should see a message to let them know why top level role cannot configure custom check
non-admin users should know they don't have permission to configure custom check. UI does not have to display message to them.
CUSTOM_CHECK_CONTROL="strict"
admin or feAdmin users can configure custom check
non-admin users should know they don't have permission to configure custom check.UI  does not have to display message to them.
NVSHAS-8326: RegScan Docker Registry disallows entry for "Registry" field
The new formly field's key was dupulicated with existing registry url field. I renamed the key
> NVSHAS-8290, NVSHAS-8326

- admin/webapp/websrc/app/common/types/common/common.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.filter.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items.component.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
Adds Vulnerabilities page filter for Containers/Infrastructure/Registry views
> NVSHAS-6656: Vulnerabilities UI option to show/hide impacted categories

- admin/webapp/websrc/app/routes/pages/login/login.component.ts
NVSHAS-8510 NV SSO thru Rancher fails since jenkins-nv-build-manager-3866
> NVSHAS-8510

- admin/webapp/websrc/app/common/services/admission-rules.service.ts
- admin/webapp/websrc/app/routes/components/admission-rules/partial/configuration-assessment-modal/configuration-assessment-modal.component.ts
NVSHAS-8489: Some grid in Admission control "Configuration Assessment " result window cannot be adjusted
NVSHAS-8524: Text overlaps in table after resizing the column headers width
NVSHAS-8505: need to present the disable status of admission control rule in pdf/csv report
> NVSHAS-8489, NVSHAS-8524, NVSHAS-8505

- admin/webapp/websrc/app/common/neuvector-formly/checkbox/checkbox.component.html
- admin/webapp/websrc/app/common/neuvector-formly/toggle/toggle.component.html
NVSHAS-8494 [UI] webhook with proxy (apply a left margin to enhance the UI appearance)
> NVSHAS-8494 

- admin/webapp/websrc/app/routes/components/federated-policy-configuration/federated-config-form/types/constants/webhook-constants.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form-config/constants/webhook-constants.ts
added a default value "false" for the boolean property "use_proxy"
> NVSHAS-8494 [UI] webhook with proxy

- admin/webapp/websrc/app/routes/network-activities/graph.service.ts
Fix the css style is not set correctly for alert action in active session dialog.
> Fix Jira case https://jira.suse.com/browse/NVSHAS-8557

- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form.component.ts
NVSHAS-8599 Popup of "Leave page without saving configuration" even no change is made
> NVSHAS-8599

- admin/src/main/scala/com/neu/api/RiskService.scala
- admin/src/main/scala/com/neu/model/Vulnerability.scala
- admin/webapp/websrc/app/common/api/risks-http.service.ts
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/risks-view-report/risk-view-report-impact-col/risk-view-report-impact-col.component.html
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/risks-view-report/risk-view-report-impact-col/risk-view-report-impact-col.component.ts
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/risks-view-report/risk-view-report-table/risk-view-report-table.component.html
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/risks-view-report/risks-view-report.component.html
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/risks-view-report/risks-view-report.component.ts
- admin/webapp/websrc/app/routes/components/vulnerabilities-grid/vulnerability-detail-dialog/vulnerability-detail-dialog.component.html
- admin/webapp/websrc/app/routes/components/vulnerabilities-grid/vulnerability-detail-dialog/vulnerability-detail-dialog.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/csv-generation/vulnerabilities-csv.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.module.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items.component.ts
NVSHAS-8610: CVEs in Security Risks pane no longer pop-up CVE data
NVSHAS-8641: Vulnerabilities/Assets view CSV and PDF reports on Security Risk > Vulnerabilities page after changes of new APIs for pagination
> NVSHAS-8610, NVSHAS-8641

- admin/webapp/websrc/app/routes/network-activities/pod-info/pod-info.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
NVSHAS-8655: unable to click link to group detail dialog in network activity page if the service name is too long
NVSHAS-8673: Security Risks pane pop-up CVE data should not pop up when initial page load
> NVSHAS-8655, NVSHAS-8673

- admin/webapp/websrc/app/routes/components/security-risk-printable-report/assets-view-report/assets-view-report-assets-platforms-table/assets-view-report-assets-platforms-table.component.html
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/assets-view-report/assets-view-report.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/csv-generation/vulnerabilities-csv.service.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
NVSHAS-8789: Chrome (only) browse may be out of memory when select "All" in Print Assets View
NVSHAS-8793: Vulnerability: Error in exporting vulnerabilities view csv file
> NVSHAS-8793, NVSHAS-8789

- cli/prog/scan.py
Add 
(1) Show all scanners' cache stat
> show scan cache_stat
(2) Show a scanner's cache index data
> show scan cache_data <scanner_id>
> Scanner cache: add CLI commands to obtain scanner cache data

- admin/webapp/websrc/app/common/styles/app/common.scss
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-item-details/compliance-item-details.component.html
- admin/webapp/websrc/app/routes/compliance/compliance.module.ts
- admin/webapp/websrc/app/routes/components/ui/risk-assets-legend/risk-assets-legend.component.html
- admin/webapp/websrc/app/routes/components/ui/risk-assets-legend/risk-assets-legend.component.spec.ts
- admin/webapp/websrc/app/routes/components/ui/risk-assets-legend/risk-assets-legend.component.ts
- admin/webapp/websrc/app/routes/components/ui/risk-assets-legend/risk-assets-legend.module.ts
- admin/webapp/websrc/app/routes/registries/registries-table/add-registry-dialog/add-registry-form-configs/constants/constants.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.module.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-details/vulnerability-items-details.component.html
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
NVSHAS-8875: Add date select popup before csv file download on Vulnerabilities page
NVSHAS-8880: Display assets icon and status color separately in the legend in Vulnerabilities and Compliance page
> NVSHAS-8875, NVSHAS-8880

- admin/webapp/websrc/app/routes/components/federated-policy-configuration/federated-config-form/types/constants/webhook-constants.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form-config/constants/webhook-constants.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table-action-cell/vulnerability-items-table-action-cell.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table-action-cell/vulnerability-items-table-action-cell.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
NVSHAS-8617 WebHooks to DataDog missing required parameters
NVSHAS-8852 Risk->vuln page, move the accept button to each vul entry
> NVSHAS-8617, NVSHAS-8852 

- admin/webapp/websrc/app/routes/registries/registry-details/registry-details-table/registry-details-table.component.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
Changed field value to **No OS** if `base_os` is empty.
> NVSHAS-8944: Failed Scan due to unsupported OS: Error message instead of blank

- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table-action-cell/vulnerability-items-table-action-cell.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table-action-cell/vulnerability-items-table-action-cell.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
fixed the issue that too many "risk/cve/profile" requests were sent in the Vulnerabilities page
> NVSHAS-8852 Risk->vuln page, move the accept button to each vul entryFeatures

- admin/webapp/websrc/app/routes/multi-cluster/joining-modal/joining-modal.component.html
- admin/webapp/websrc/app/routes/multi-cluster/joining-modal/joining-modal.component.ts
[UI][Multiple Clusters][Join] After pasting token, "Primary Cluster Server" and "Primary Cluster Port" don't appear automatically
> NVSHAS-8965

- admin/webapp/websrc/app/frame/header/header.component.html
- admin/webapp/websrc/app/frame/header/header.component.ts
- admin/webapp/websrc/app/routes/components/users-grid/users-grid.component.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
NVSHAS-9012: Displaying Rancher SSO users on NV UI that have the same user name
NVSHAS-8939: Provide an option on NV UI so that Rancher SSO session user can drop current jwt token (i.e. logout)
> NVSHAS-9012, NVSHAS-8939

- admin/webapp/websrc/app/routes/components/groups/partial/add-edit-group-modal/add-edit-group-modal.component.html
- admin/webapp/websrc/app/routes/components/groups/partial/add-edit-group-modal/add-edit-group-modal.component.ts
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/assets-view-report/assets-view-report-assets-images-table/assets-view-report-assets-images-table.component.html
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/assets-view-report/assets-view-report-assets-nodes-table/assets-view-report-assets-nodes-table.component.html
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/assets-view-report/assets-view-report-assets-pods-table/assets-view-report-assets-pods-table.component.html
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
NVSHAS-9103: there is typo in warning message when delete Monitoring Metric Threshold values in add/edit group window
NVSHAS-9085: Assets View PDF report shows 0% even though the workload contains vulnerabilites (CHange wording according to comment)
> NVSHAS-9085, NVSHAS-9103

- admin/webapp/websrc/app/routes/components/security-risk-printable-report/risks-view-report/risks-view-report.component.html
- admin/webapp/websrc/app/routes/components/security-risk-printable-report/risks-view-report/risks-view-report.component.ts
- admin/webapp/websrc/app/routes/components/users-grid/add-edit-user-dialog/add-edit-user-dialog.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.html
NVSHAS-9246: Filtering for CSV/PDF export does not work.
NVSHAS-8836: Rancher/NeuVector SSO integration should work for non-admin users (UI) (Fixed bugs for showing Rancher permissions)
> NVSHAS-9246, NVSHAS-8836

- admin/webapp/websrc/app/common/neuvector-formly/card/card.component.html
- admin/webapp/websrc/app/common/neuvector-formly/card/card.component.ts
- admin/webapp/websrc/app/common/neuvector-formly/formlyValidators.ts
- admin/webapp/websrc/app/common/neuvector-formly/neuvector-formly.module.ts
- admin/webapp/websrc/app/common/neuvector-formly/text-area/text-area.component.html
- admin/webapp/websrc/app/common/types/settings/certificate.ts
- admin/webapp/websrc/app/common/types/settings/config-vo.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form-config/constants/tls-constants.ts
- admin/webapp/websrc/app/routes/settings/configuration/configuration.component.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
Add the deserialize function for the certification, and show the deserialized information on the certificate editing table.
> NVSHAS-9219: adjustments for certificate manifest column

- scripts/support.py
> Revert "NVSHAS-9264: update support.py for new REST APIs in NV 5.4"

- admin/webapp/websrc/app/common/api/risks-http.service.ts
- admin/webapp/websrc/app/common/directives/remote-grid-binding.directive.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.filter.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.service.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.html
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
Adjusted data preload methodology by making it to request separately instead of 300 data in one request.
Preload forward
Preload backward
> NVSHAS-9098: Enhance risk page loading user experience

- admin/webapp/websrc/app/routes/compliance-profile/compliance-profile-templates/compliance-profile-templates-table/compliance-profile-templates-table.component.ts
- admin/webapp/websrc/app/routes/compliance/compliance.filter.service.ts
- admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.ts
NVSHAS-9334: [Compliance Profile Page][Compliance Filter] The filtered result is not expected
NVSHAS-9331: NV SSO user with fed(r/w) and registryscan(r/w) is not able start the scan, start scan button is not displayed
> NVSHAS-9331, NVSHAS-9334

- cli/prog/controller.py
- cli/prog/enforcer.py
- cli/prog/system.py
1. Add set enforcer/controller log_level command with choice (error, warn, info, debug)
2. Add set system log_level enforcers/controllers command with choice (error, warn, info, debug)
> NVSHAS-7687 & 9006

- admin/webapp/websrc/app/routes/network-activities/edge-details/edge-details.component.html
- admin/webapp/websrc/app/routes/network-activities/edge-details/edge-details.component.ts
- admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.html
- admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.ts
- admin/webapp/websrc/app/routes/registries/registries.component.ts
NVSHAS-9345: SSO: View all scanned images is not working on SSO session
NVSHAS-9349: Unmatched count of total registry items 
NVSHAS-9231: It isn't possible to review network rules for some routes in the Network Activity tab
> NVSHAS-9345, NVSHAS-9349, NVSHAS-9231

- admin/webapp/websrc/app/app.component.ts
- admin/webapp/websrc/app/common/utils/auth.utils.ts
- admin/webapp/websrc/app/frame/header/header.component.ts
NVSHAS-9373 NV SSO user with fed(r)+ admissioncontrol(r) permissions can click Test in admission control page on managed cluster UI
NVSHAS-9386 NV SSO user with fed(r)+ all permission resources except cluster/namespace(r/w) permissions unexpectedly can edit LDAP & Password Profile pages on managed cluster
> NVSHAS-9373, NVSHAS-9386

- admin/webapp/websrc/app/routes/pages/login/alert/alert.component.html
- admin/webapp/websrc/app/routes/pages/login/alert/alert.component.scss
- admin/webapp/websrc/app/routes/pages/login/alert/alert.component.spec.ts
- admin/webapp/websrc/app/routes/pages/login/alert/alert.component.ts
- admin/webapp/websrc/app/routes/pages/login/eula/eula.component.html
- admin/webapp/websrc/app/routes/pages/login/login.component.html
- admin/webapp/websrc/app/routes/pages/login/login.component.scss
- admin/webapp/websrc/app/routes/pages/login/login.component.ts
- admin/webapp/websrc/app/routes/pages/pages.module.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
1. Display RBAC alert messages on the login page if applicable
2. Show the details of the RBAC role/rolebinding errors and the command to retrieve password from K8s Secret
> NVSHAS-9212 Display alerting msg in GET(/v1/eula) if the neuvector-binding-secret role(binding) is incorrect

- admin/webapp/websrc/app/routes/registries/registries-table/registry-table-status-cell/registry-table-status-cell.component.html
- admin/webapp/websrc/app/routes/registries/registries-table/registry-table-status-cell/registry-table-status-cell.component.ts
- admin/webapp/websrc/app/routes/registries/registries.component.scss
- admin/webapp/websrc/app/routes/registries/registry-details/registry-details-table/registry-details-table-status-cell/registry-details-table-status-cell.component.html
- admin/webapp/websrc/app/routes/registries/registry-details/registry-details-table/registry-details-table-status-cell/registry-details-table-status-cell.component.ts
Add an information icon and show the copyable result for the error scan result of the registries page.
> NVSHAS-9367: Enhance error messages when registry fails to be connected

- admin/src/main/scala/com/neu/model/Group.scala
- admin/src/main/scala/com/neu/model/GroupJsonProtocol.scala
- admin/webapp/websrc/app/common/types/settings/remote-repository.ts
- admin/webapp/websrc/app/frame/frame.service.spec.ts
- admin/webapp/websrc/app/frame/frame.service.ts
- admin/webapp/websrc/app/frame/header/header.component.ts
- admin/webapp/websrc/app/routes/components/export-options/export-options.component.html
- admin/webapp/websrc/app/routes/components/export-options/export-options.component.ts
- admin/webapp/websrc/app/routes/components/groups/groups.component.html
- admin/webapp/websrc/app/routes/components/groups/groups.component.ts
- admin/webapp/websrc/app/routes/network-activities/network-activities.component.ts
NVSHAS-9475: Background grid print is not fully covering when menu is collpsed.
NVSHAS-9465: Export/Import groups by using either network policy mode and process profile mode
> NVSHAS-9465,NVSHAS-9475

- admin/webapp/websrc/app/routes/components/admission-rules/partial/action-buttons/action-buttons.component.ts
- admin/webapp/websrc/app/routes/components/response-rules/partial/action-buttons/action-buttons.component.ts
- admin/webapp/websrc/app/routes/components/security-risk-panel/partial/score-instruction/score-instruction.component.ts
- admin/webapp/websrc/app/routes/components/users-grid/users-grid.component.ts
- admin/webapp/websrc/app/routes/dlp-sensors/dlp-sensors.component.ts
- admin/webapp/websrc/app/routes/dlp-sensors/partial/pattern-action-buttons/pattern-action-buttons.component.ts
- admin/webapp/websrc/app/routes/dlp-sensors/partial/rule-action-buttons/rule-action-buttons.component.ts
- admin/webapp/websrc/app/routes/dlp-sensors/partial/sensor-action-buttons/sensor-action-buttons.component.ts
- admin/webapp/websrc/app/routes/waf-sensors/partial/pattern-action-buttons/pattern-action-buttons.component.ts
- admin/webapp/websrc/app/routes/waf-sensors/partial/rule-action-buttons/rule-action-buttons.component.ts
- admin/webapp/websrc/app/routes/waf-sensors/partial/sensor-action-buttons/sensor-action-buttons.component.ts
NVSHAS-9566: Removal confirmation dialog is stuck after click OK
NVSHAS-9561: Dashboard board overall security score should match to actual score
> NVSHAS-9561, NVSHAS-9566

- Makefile
> Revert "NVSHAS-9537: Change existing builders base image to BCI for AMD64 - m…"

- admin/src/main/scala/com/neu/api/authentication/SamlAuthApi.scala
- admin/webapp/websrc/app/routes/components/apikeys-grid/apikeys-grid.component.ts
- admin/webapp/websrc/app/routes/components/network-rules/partial/action-buttons/action-buttons.component.ts
- admin/webapp/websrc/app/routes/components/users-grid/users-grid.component.ts
- admin/webapp/websrc/app/routes/dlp-sensors/dlp-sensors.component.ts
- admin/webapp/websrc/app/routes/signature-verifiers/partial/signature-action-buttons/signature-action-buttons.component.ts
- admin/webapp/websrc/app/routes/signature-verifiers/signature-verifiers.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.ts
- admin/webapp/websrc/app/routes/waf-sensors/waf-sensors.component.ts
NVSHAS-9636: ERROR TypeError: after editing DLP / WAF sensor
NVSHAS-9640: Logout produces 404 error from token authentication server
NVSHAS-9639: Undelete network rule produce 'getDisplayedRowAtIndex' type error
NVSHAS-9635: Delete dialog does not dismiss after OK confirmation
> NVSHAS-9636,NVSHAS-9640,NVSHAS-9639,NVSHAS-9635

- admin/webapp/websrc/app/common/constants/map.constant.ts
- admin/webapp/websrc/app/common/styles/app/common.scss
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items-charts/compliance-items-charts.component.ts
- admin/webapp/websrc/app/routes/compliance/compliance-items/compliance-items.component.ts
- admin/webapp/websrc/app/routes/compliance/compliance.service.ts
- admin/webapp/websrc/app/routes/components/events-grid/events-grid.component.ts
- admin/webapp/websrc/app/routes/components/network-rules/partial/action-buttons/action-buttons.component.ts
- admin/webapp/websrc/app/routes/components/risk-report-grid/risk-report-grid.component.ts
- admin/webapp/websrc/app/routes/signature-verifiers/partial/signature-action-buttons/signature-action-buttons.component.ts
- admin/webapp/websrc/app/routes/vulnerabilities/vulnerabilities.component.ts
NVSHAS-9641: [UI] UI would call /vulasset fail when change Vulnerabilties View
NVSHAS-9642: [UI] Compliance Severity Distribution chart missing Manual status
NVSHAS-9643: [UI] Can't sort by location on Notifications Risk Reports/Events page
> NVSHAS-9641, NVSHAS-9642, NVSHAS-9643

- admin/src/main/scala/com/neu/api/Api.scala
- admin/src/main/scala/com/neu/client/RestClient.scala
- admin/src/main/scala/com/neu/core/ClientSslConfig.scala
- admin/src/main/scala/com/neu/service/authentication/SuseAuthService.scala
- admin/webapp/websrc/app/routes/components/network-rules/partial/action-buttons/action-buttons.component.ts
- admin/webapp/websrc/app/routes/signature-verifiers/partial/signature-action-buttons/signature-action-buttons.component.ts
1. Rancher cookie parsing issue with wrong name filter.
2. Incorrect error response status of login function.
> NVSHAS-9644: NV's Rancher SSO fails

- admin/webapp/websrc/app/routes/components/file-access-rules/partial/predefined-file-access-rules-modal/operation-cell/operation-cell/operation-cell.component.ts
- admin/webapp/websrc/app/routes/components/file-access-rules/partial/predefined-file-access-rules-modal/predefined-file-access-rules-modal.component.ts
- admin/webapp/websrc/app/routes/components/group-details/partial/custom-check-action-button/custom-check-action-button.component.ts
- admin/webapp/websrc/app/routes/components/group-details/partial/custom-check/custom-check.component.ts
NVSHAS-9665: File Access rule: Delete predefined rules produces "setRowData" error
NVSHAS-9664: Policy Group: Delete custom script produces "setRowData" TypeError
> NVSHAS-9665, NVSHAS-9664

- Dockerfile.manager
- Makefile
- admin/src/main/scala/com/neu/core/MySslConfiguration.scala
- package/Dockerfile
- package/build_manager.sh
- package/entrypoint.sh
Separated java.security file usage from fips and non-fips at the execution command.
> NVSHAS-9750: WebUI is not working with standalone manager run as docker container.

- admin/webapp/websrc/app/common/neuvector-formly/formlyValidators.ts
- admin/webapp/websrc/app/common/neuvector-formly/neuvector-formly.module.ts
- admin/webapp/websrc/app/routes/registries/registries-table/add-registry-dialog/add-registry-form-configs/configs/github-container-registry.config.ts
- admin/webapp/websrc/app/routes/registries/registries-table/add-registry-dialog/add-registry-form-configs/constants/constants.ts
- admin/webapp/websrc/app/routes/registries/registries-table/add-registry-dialog/add-registry-form-configs/index.ts
Added a validator using the regex /^(([a-z0-9](?:[._-]?[a-z0-9]+)*)\/)+([a-z0-9_.*:-]*)$/ to validate the input format
> NVSHAS-9845 UI: Github Registry type should limit filter to scan whole repos

- admin/src/main/scala/com/neu/model/DashboardJsonProtocal.scala
- admin/src/main/scala/com/neu/service/dashboard/DashboardService.scala
Fixes Dashboard Auto Scan button GET logic
> fix: NVSHAS-9835: UI for Disable auto scan for node

- admin/src/main/scala/com/neu/api/authentication/SuseAuthApi.scala
- admin/src/main/scala/com/neu/api/policy/PolicyApi.scala
- admin/src/main/scala/com/neu/service/authentication/AuthServiceFactory.scala
- admin/src/main/scala/com/neu/service/authentication/OpenIdAuthService.scala
- admin/src/main/scala/com/neu/service/authentication/SamlAuthService.scala
- admin/src/main/scala/com/neu/service/authentication/SuseAuthService.scala
- admin/src/main/scala/com/neu/service/policy/PolicyService.scala
- admin/webapp/websrc/app/app.component.ts
- admin/webapp/websrc/app/common/constants/path.constant.ts
- admin/webapp/websrc/app/common/services/multi-cluster.service.ts
- admin/webapp/websrc/app/common/services/registries.service.ts
- admin/webapp/websrc/app/common/types/registries/registries.ts
- admin/webapp/websrc/app/frame/header/header.component.ts
- admin/webapp/websrc/app/routes/pages/login/login.component.ts
- admin/webapp/websrc/app/routes/registries/regestries-communication.service.ts
- admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.html
- admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.ts
- admin/webapp/websrc/app/routes/registries/registries.component.ts
- admin/webapp/websrc/app/routes/registries/registry-details/registry-details.component.html
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
NVSHAS-9915: Show scan result from harbor scanner module in Neuvector UI.
NVSHAS-9909: "Signed Out - Go to loading page" Message displayed when using NeuVector Rancher NavLink
> NVSHAS-9909, NVSHAS-9915

- admin/src/main/scala/com/neu/api/authentication/ExtraAuthApi.scala
- admin/src/main/scala/com/neu/client/RestClient.scala
- admin/src/main/scala/com/neu/model/SystemConfig.scala
- admin/src/main/scala/com/neu/model/SystemConfigJsonProtocol.scala
- admin/src/main/scala/com/neu/service/authentication/ExtraAuthService.scala
- admin/webapp/websrc/app/common/services/auth.service.ts
- admin/webapp/websrc/app/common/types/settings/config.ts
- admin/webapp/websrc/app/routes/pages/login/login.component.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form-config/constants/config-constants.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form-config/index.ts
- admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form.component.ts
- admin/webapp/websrc/assets/i18n/en-common.json
- admin/webapp/websrc/assets/i18n/zh_cn-common.json
NVSHAS-10066: First time login does not show link for bootstrap helper when user directly access UI in Rancher deployment
NVSHAS-10065: Add a configuration setting on UI for allowing ns user to export
> NVSHAS-10065, NVSHAS-10066
