cli/prog/group.py
CLI commands:
show service
create service 
set service
=> Zero-Drift: add service handler on setting and displaying baseline_profile attribute.

cli/prog/system.py
Sync CLI to minimum 3600 seconds to match UI representation.
=> NV6324: the inconsistent setting of Service Group Mode Automation

admin/src/main/scala/com/neu/api/BaseService.scala
Fixes a typo on authSSODisabledError when Rancher/OpenShift auth is disabled.
Resolves https://github.com/neuvector/neuvector/issues/299
=> Fix typo on authSSODisabledError

admin/webapp/root/app_src/js/nv/event/securityEventsController.js, admin/webapp/root/app_src/js/nv/event/threatController.js
Fix Jira case 6265: UI Issue: PCAP downloads are named "pocket_nnnnnnn"
=> UI Issue: PCAP downloads are named "pocket_nnnnnnn"

admin/webapp/websrc/app/common/api/auth-http.service.ts, admin/webapp/websrc/app/common/services/settings.service.ts, admin/webapp/websrc/app/common/types/settings/settings.ts, admin/webapp/websrc/app/routes/components/containers-grid/containers-grid.component.ts, admin/webapp/websrc/app/routes/registries/regestries-communication.service.ts, admin/webapp/websrc/app/routes/registries/registries-table/add-registry-dialog/add-registry-dialog.component.html, admin/webapp/websrc/app/routes/registries/registries-table/add-registry-dialog/add-registry-dialog.component.ts, admin/webapp/websrc/app/routes/registries/registries-table/registries-table-buttons/registries-table-buttons.component.html, admin/webapp/websrc/app/routes/registries/registries-table/registries-table-buttons/registries-table-buttons.component.ts, admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.ts, admin/webapp/websrc/app/routes/registries/registry-details/registry-overview/registry-overview.component.ts, admin/webapp/websrc/app/routes/settings/ldap/ldap-form/ldap-form.component.ts, admin/webapp/websrc/app/routes/settings/ldap/test-connection-dialog/test-connection-dialog.component.ts, admin/webapp/websrc/app/routes/settings/openid/openid-form/openid-form.component.ts, admin/webapp/websrc/app/routes/settings/saml/saml-form/saml-form.component.ts
Addresses NV-5.1 cases:
- NVSHAS-6837: odic is unable saved successfully
- NVSHAS-6923: Error status code for creating registry is not handled well by UI
- NVSHAS-6849: child container is unable to show under parent one in containers page
- NVSHAS-6894: Settings -> LDAP/SAML/OIDC pages do not work as expected
- NVSHAS-6960: Refresh icon is always running after click refresh icon in Assets->Registries UI
- NVSHAS-6867: the tag info is missing in assets > registries > overview page
- NVSHAS-6897: unable to show tooltip when moving mouse over on icon in many pages
- NVSHAS-6879: the view icon is missing in assets > registries page if reader user is logged in
=> NV5.1 Cases

cli/prog/domain.py
Append Nameapce's labels via a REST API call: GET "/v1/domain"
(1) Add REST entry:
type RESTDomain struct {
.........
Labels map[string]string json:"labels"
}
(2) Update CLI response: "show domain".
(3) Update swagger data.
=> NVSHAS-6695: Expose namespace label in REST API

admin/src/main/scala/com/neu/model/AuthTokenJsonProtocol.scala, admin/src/main/scala/com/neu/model/SamlServer.scala, admin/webapp/websrc/app/common/types/settings/settings.ts, admin/webapp/websrc/app/routes/settings/saml/saml-form/saml-form.component.html, admin/webapp/websrc/app/routes/settings/saml/saml-form/saml-form.component.scss, admin/webapp/websrc/app/routes/settings/saml/saml-form/saml-form.component.ts, admin/webapp/websrc/app/routes/settings/saml/saml.module.ts, admin/webapp/websrc/assets/i18n/en.json, admin/webapp/websrc/assets/i18n/zh_cn.json
Adds UI support for SAML config field `x509_cert_extras`. References neuvector/neuvector#678
=> NVSHAS-7335: Allow NeuVector to set several ADFS certificates in parallel in x.509 certificate field.

admin/webapp/websrc/app/app.component.ts
This is a timing issue when page reloading was triggered after it is navigated to login page.
A timeout latency can resolve the issue.
=> NVSHAS-8511: [Manager] After Manager session timeout, NeuVector browser sessions gets into infinite loop

cli/prog/sigstore.py
In the CLI, when `rootless_keypairs_only` is set to true, `is_private` will always be set to false.
Also, create a new `type` column when showing the `root_of_trust` details, that will show either `private`, `public`, or `rootless_keypairs_only`.
=> rootless_keypairs_only override + reformat root of trust show command

admin/webapp/websrc/app/common/types/dashboard/dashboard.ts, admin/webapp/websrc/app/common/utils/common.utils.ts, admin/webapp/websrc/app/routes/components/exposed-servicepod-conv-grid/conversation-entry-list/conversation-entry-list.component.ts
fixed an issue: 
When a service exists across multiple pods, and each pod has vulnerabilities, the overall vulnerability of the service should be the aggregate of all these pod's vulnerability number.
=> NVSHAS-8475 Indicate if the service is vulnerable in dashboard ingress/egress exposure section

admin/src/main/scala/com/neu/api/AuthenticationService.scala, admin/src/main/scala/com/neu/api/RiskService.scala, admin/src/main/scala/com/neu/core/MySslConfiguration.scala, admin/webapp/websrc/app/core/interceptor/timeout.interceptor.ts, admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.html, admin/webapp/websrc/app/routes/registries/registries-table/registries-table.component.ts, common/src/main/resources/application.conf, common/src/main/scala/com/neu/core/CommonSettings.scala
NVSHAS-9122: Neuvector master logs out any time use "Multiple Cluster" using Rancher SSO login
NVSHAS-9213: scan result cannot be displayed in UI after click View all scanned images in NV UI registries page
NVSHAS-9214: Prompt user to re-login Rancher Console when NV controller gets 410 from Rancher API server for SSO
NVSHAS-9217: Manager exception
NVSHAS-7522: Easy Image navigation through registries (Easy Image navigation through registries(REST API URL changed))
=> NVSHAS-9122,NVSHAS-9213,NVSHAS-9214,NVSHAS-9217,NVSHAS-7522

admin/webapp/websrc/app/common/types/common/common.ts, admin/webapp/websrc/app/routes/components/global-notifications/global-notifications.component.html, admin/webapp/websrc/app/routes/components/global-notifications/global-notifications.component.ts
1. Revised to use the enum type for the reduction of the free typing string of the code, and gaining some more resilient usages.
Objects:
```
export enum GlobalNotificationType {
RBAC_NOTIFICATION = 'RBAC_NOTIFICATION',
MANAGER_NOTIFICATION = 'MANAGER_NOTIFICATION',
USER_NOTIFICATION = 'USER_NOTIFICATION'
}
export interface GlobalNotification {
type: GlobalNotificationType;
name: string;
key: string;
message: string;
link: string;
labelClass: string;
accepted: boolean;
unClamped: boolean;
}
```
Data initialization (GlobalNotification):
```
if (this.rbacData.acceptable_alerts) {
Object.keys(this.rbacData.acceptable_alerts).forEach(rbacAlertType => {
const alert = this.rbacData.acceptable_alerts[rbacAlertType];
if (alert && Object.keys(alert).length > 0) {
Object.keys(alert).forEach(key => …
```
=> NVSHAS-9239: Global Notification Rbac notification should not disappear if the accept operation is not successful.

admin/webapp/websrc/app/routes/settings/configuration/configuration.component.ts
A quick fix to allow null `cacerts` from backend.
=> NVSHAS-9219 allow null cacerts

admin/src/main/scala/com/neu/model/SystemConfig.scala, admin/src/main/scala/com/neu/model/SystemConfigJsonProtocol.scala, admin/webapp/websrc/app/common/types/settings/config.ts, admin/webapp/websrc/app/routes/settings/configuration/config-form/config-form.component.ts
Problem
To fix NVSHAS-8539 "Reconfig proxy setting lose password", 'registry_http(s)_proxy_cfg' has been added to 'RESTSystemConfigProxyCfgV2', UI must update the payload structure when calling the '/v2/system/config' patch endpoint to ensure that the proxy settings are correctly updated on the configuration page without losing the password.
Solution
When the UI calls the '/v2/system/config' patch endpoint, it sends a payload with 'config_v2.proxy_cfg.registry_http_proxy_cfg.password' and 'config_v2.proxy_cfg.registry_https_proxy_cfg.password' set to null to save the proxy settings without modifying the existing passwords.
=> NVSHAS-8539 Reconfig proxy setting lose password

admin/webapp/websrc/assets/i18n/en-common.json, admin/webapp/websrc/assets/i18n/zh_cn-common.json
Problem:
The settings->Users page displays the raw string "role.permissions.FED" instead of a translated label.
Solution:
Added a translation entry for the "FED" permission ID in the i18n files.
=> NVSHAS-9297 raw permission string is displayed on SSO UI

admin/webapp/websrc/app/routes/components/global-notifications/global-notifications.component.ts
=> NVSHAS-9258: remove redirect link of tls self-signed cert expiring alert, use NV docs' instructions instead

admin/webapp/websrc/app/common/utils/auth.utils.ts, admin/webapp/websrc/app/routes/components/admission-rules/admission-rules.component.html, admin/webapp/websrc/app/routes/components/admission-rules/admission-rules.component.ts, admin/webapp/websrc/app/routes/groups-page/groups-page.component.ts
[NVSHAS-9373] NV SSO user with fed(r)+admissioncontrol(r) permissions can click Test in admission control page on managed cluster UI
[NVSHAS-9374] NV SSO user with fed(r)+non-admissioncontrol(r) permissions see "Loading" in admission control page on master cluster UI
[NVSHAS-9378] NV SSO user with fed(r)+registryscan/authentication/authorization(r/w) permissions unexpectedly can click 'Edit/Delete/Start Scan' of non-fed registry & 'Add/Edit/Delete' buttons of many pages on managed cluster
[NVSHAS-9386]NV SSO user with fed(r)+ all permission resources except cluster/namespace(r/w) permissions unexpectedly can edit LDAP & Password Profile pages on managed cluster
[NVSHAS-9385]NV SSO user with fed(r)+vulnerability/compliance/runtimepolicy/runtimescan/systemconfig(r/w) permissions …
=> NVSHAS-9373, NVSHAS-9374, NVSHAS-9378, NVSHAS-9385 and NVSHAS-9386

Makefile
Change existing builders base image to BCI with BUILD_IMAGE_TAG to v3
=> NVSHAS-9537: Change BUILD_IMAGE_TAG=v3 for manager image

admin/src/main/scala/com/neu/core/MySslConfiguration.scala
Replaced the package we originally used sun.security.util.DerInputStream to org.bouncycastle.asn1.ASN1InputStream for parsing private key to solve the incompatibility issue in JDK 17.
Notes: 
1. The error occurs because Java 17 enforces stronger module encapsulation for internal sun.security.* packages.
2. Using internal APIs is discouraged as they may change or be removed in future Java releases, and existing potential security issues as well.
=> NVSHAS-9623: SSL private key parsing issue from using DerInputStream of sun.security with Scala 3 and JDK 17.

admin/webapp/websrc/app/common/utils/app.utils.ts
Issue: 
When a file is downloaded using the Chrome browser, underscores are unexpectedly appended to the beginning and end of the filename. 
Cause:  
The underscores are being introduced because the filename is being parsed with leading and trailing double quotes. These quotes are interpreted as part of the filename, causing the undesired underscores.
Solution: 
To resolve this, we need to trim any leading and trailing double quotes from the filename (if they exist).
=> NVSHAS-9647 Default group export file name format changes

admin/src/main/scala/com/neu/service/DefaultJsonFormats.scala, admin/webapp/websrc/app/routes/components/file-access-rules/partial/predefined-file-access-rules-modal/operation-cell/operation-cell/operation-cell.component.ts, build.sbt
1. Plain text response double quotes issue.
Added custom marshaller to avoid double quotes.
2. Java unnamed library issue in sbt run.
Added add-opens Java API usage into build.sbt.
```
lazy val commonSettings = Seq(
javaOptions ++= Seq(
"--add-opens=java.base/java.lang=ALL-UNNAMED",
"--add-opens=java.base/java.util=ALL-UNNAMED",
"--add-opens=java.base/java.io=ALL-UNNAMED"
),
Test / javaOptions ++= Seq(
"--add-opens=java.base/java.lang=ALL-UNNAMED",
"--add-opens=java.base/java.util=ALL-UNNAMED",
"--add-opens=java.base/java.io=ALL-UNNAMED"
),
run / javaOptions ++= Seq(
"--add-opens=java.base/java.lang=ALL-UNNAMED",
"--add-opens=java.base/java.util=ALL-UNNAMED",
"--add-opens=java.base/java.io=ALL-UNNAMED"
)
)
```
Note: Note: Java API usage is a kind of workaround that should be revised if …
=> NVSHAS-9670: Plain text response double quotes issue and java unnamed library issue in sbt run.

admin/webapp/websrc/app/routes/components/vulnerabilities-grid/vulnerabilities-grid.component.ts, admin/webapp/websrc/app/routes/containers/container-details/container-details.component.html, admin/webapp/websrc/app/routes/containers/container-details/container-details.component.scss, admin/webapp/websrc/app/routes/containers/container-details/container-details.component.ts, admin/webapp/websrc/app/routes/nodes/node-details/node-details.component.html, admin/webapp/websrc/app/routes/nodes/node-details/node-details.component.scss, admin/webapp/websrc/app/routes/nodes/node-details/node-details.component.ts, admin/webapp/websrc/app/routes/platforms/platform-details/platform-details.component.html, admin/webapp/websrc/app/routes/platforms/platform-details/platform-details.component.ts, admin/webapp/websrc/app/routes/registries/registry-details/registry-details-table/registry-details-dialog/registry-vulnerabilities/registry-vulnerabilities.component.html, admin/webapp/websrc/app/routes/registries/registry-details/registry-details-table/registry-details-dialog/registry-vulnerabilities/registry-vulnerabilities.component.ts, admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table.component.html
This PR introduces a feature that allows users to select a specific vulnerability score to be used for all assets (Platform, Nodes, Container, Registry).
Changes:
- A dropdown (or equivalent) has been added to the UI for score selection
=> NVSHAS-9590 To choose which vulnerability score for all assets.

package/Dockerfile, package/build_manager.sh
upgrade npm from v10.8.2 to v10.9.2
exclude node_moduels of usr/lib64 of package/Dockerfile build image
clean up unused scripts of package/build_manager.sh
=> fix: fix npm package severity issue

admin/src/main/scala/com/neu/api/Api.scala, admin/src/main/scala/com/neu/core/ClientSslConfig.scala, admin/webapp/websrc/app/common/api/config-http.service.ts, admin/webapp/websrc/app/routes/settings/configuration/csp-support-form/csp-support-form.component.ts
Fix to correctly show up error message from return error response entity for custom exception instead of error reason.
Error showing correctly in csp-support panel of configuration.
Error showing correctly in registry page.
=> NVSHAS-9704/NVSHAS-9721: error messages are not showing up

Dockerfile.manager, Makefile, admin/src/main/scala/com/neu/core/MySslConfiguration.scala, package/Dockerfile, package/build_manager.sh, package/entrypoint.sh
separated java.security file usage from fips and non-fips at the execution command
=> NVSHAS-9750: WebUI is not working with standalone manager run as docker container. (5.4.2 Cherry-pick)

admin/src/main/scala/com/neu/api/Api.scala, admin/src/main/scala/com/neu/core/Core.scala, package/entrypoint.sh
Before fix: 
```
curl 'https://localhost:8443/host' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Accept-Language: en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7' \
-H 'Cache-Control: no-cache' \
-H 'Connection: keep-alive' \
-H 'Cookie: R_PCS=light; R_REDIRECTED=true; R_LOCALE=en-us; CSRF=*****' \
-H 'Pragma: no-cache' \
-H 'Referer: https://localhost:8443/' \
-H 'Sec-Fetch-Dest: empty' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
-H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'sec-ch-ua-platform: "macOS"' \
-H 'token: *****' \
-H "Large-Header: $(printf '%s' $(head -c …
```
=> NVSHAS-9780: NeuVector single sign on not working with Rancher NavLink

cli/cli
CLI: update the default shell from "sh" to "bash"
=> NVSHAS-9325: update CLI shell to bash

admin/src/main/scala/com/neu/core/Core.scala, admin/src/main/scala/com/neu/core/MySslConfiguration.scala
Ref: [https://github.com/neuvector/neuvector/issues/1757](url)
The issue is from the default SSL context check by Pekko, fixed by setting the default SSL context of non-SSL operations.
Revised Log:
```
manager  | FIPS mode detected (via /proc/sys/crypto/fips_enabled).
manager  | 2025-01-29 14:31:15,593|INFO |MANAGER|apache.pekko.event.slf4j.Slf4jLogger(applyOrElse:117): Slf4jLogger started
manager  | Jan 29, 2025 2:31:17 PM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
manager  | INFO: Found string security property [jdk.tls.disabledAlgorithms]: DH keySize < 2048, TLSv1.1, TLSv1, SSLv3, SSLv2, DHE_DSS, RSA_EXPORT, DHE_DSS_EXPORT, DHE_RSA_EXPORT, DH_DSS_EXPORT, DH_RSA_EXPORT, DH_anon, ECDH_anon, DH_RSA, DH_DSS, ECDH, 3DES_EDE_CBC, DES_CBC, RC4_40, RC4_128, …
```
=> NVSHAS-9801: FIPS mode + manager.env.ssl=false causes Manager to error out.

scripts/support
Update it with the default shell of the BCI: bash.
=> NV9325: follow-up, update default shell to bash

admin/webapp/websrc/assets/i18n/en-common.json
It is the "namespace" (which the repos live under) that is required to be specified. In GitHub these namespaces can be either users or organizations.
=> NVSHAS-9838: clarify copy for github filter hint

admin/webapp/websrc/app/common/neuvector-formly/formlyValidators.ts
Modify the Github Registry Filter Validation Regex to `^(([a-z0-9](?:[._-]?[a-z0-9]+)*)\/)+([a-z0-9_.*:-]+)$` (adjust the quantifier from * to + ) , which prevents cases like "myrepo/" a trailing slash without anything after
=> NVSHAS-9845 UI: Github Registry type should limit filter to scan whole repos

admin/webapp/websrc/app/common/types/common/common.ts, admin/webapp/websrc/app/routes/vulnerabilities/vulnerability-items/vulnerability-items-table/vulnerability-items-table-filter/vulnerability-items-table-filter.component.html, admin/webapp/websrc/assets/i18n/en-common.json, admin/webapp/websrc/assets/i18n/zh_cn-common.json
Adds "With All Fixed" option to Vulnerabilities advanced filter. The behavior is:
- "With Fix" shows CVEs where any package contains a "Fix Version"
- "With All Fixed" shows CVEs where all packages contain a "Fix Version"
- "Without Fix" shows CVEs where all packages do not contain a "Fix Version"
=> NVSHAS-9873: UI Advanced Filter search issue in NeuVector 5.4.2

package/entrypoint.sh
This reverts commit 52f3d64801938d196a86bd7ad9490d0be71f7317.
=> Revert "fix typo in java security properties param"

package/Dockerfile
This allows us to build it using BCI 15.6 images
=> chore: pin jdk images
